Add flush to arbitrary file
foundry-rs/foundry-fork-db pull request #12
Opened 2024-07-20 12:41 UTC by Ethanol48

## Motivation

In issue #6 was discussed of adding public functions to change state in the db, and because of this I think it makes sense to have a way to have a cache file without the need to set it in the `db`, or in the case that we want to preserve the cache from the previous session without being altered.

## Solution

Added in `flush_to(cache_path)` `JsonBlockCacheDB`  implementation a function that lets you dump the db in a determined file.

Test are still to be implemented to test if the file is written programmatically, but testing this feature by my own works as intented.

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation

2024-07-20 13:00 UTC, Ethanol48 commented
Added minimal documentation.

2024-07-20 13:00 UTC, Ethanol48 commented
Pending changing to `CHANGELOG.md`

2024-07-20 13:53 UTC, Ethanol48 commented
I’m sorry for any notifications sent, I was using my phone and the application doesn’t have much support and made some mistakes, my apologies.

2024-07-22 12:47 UTC, mattsse commented on src/backend.rs
> +    pub fn flush_cache_to(&self, cache_path: Option<PathBuf>) {
lets make this accept PathBuf

2024-07-22 12:47 UTC, mattsse commented on src/backend.rs
> +    pub fn flush_cache_to(&self, cache_path: Option<PathBuf>) {
also docs can't hurt here

2024-07-22 12:48 UTC, mattsse commented on src/cache.rs
> +        let Some(path) = cache_path else {
we should reuse this in the existing flush function so that we don't duplicate this

2024-07-22 14:13 UTC, Ethanol48 commented
Done 👍🏼

2024-07-22 16:04 UTC, DaniPopes requested changes

2024-07-22 16:04 UTC, DaniPopes commented on src/backend.rs
> +    pub fn flush_cache_to(&self, cache_path: PathBuf) {
Should be `&Path`.

2024-07-22 16:04 UTC, DaniPopes commented on src/cache.rs
> +    pub fn flush_to(&self, cache_path: PathBuf) {
Should be `&Path`.

2024-07-23 14:45 UTC, mattsse approved these changes
lgtm!

2024-07-23 14:50 UTC, merged