replace bounded channel with unbounded channel
foundry-rs/foundry-fork-db pull request #18
Opened 2024-08-09 16:31 UTC by nkysg

## Motivation
Closes https://github.com/foundry-rs/foundry-fork-db/issues/14

## Solution

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

2024-08-09 18:25 UTC, mattsse requested changes

2024-08-09 18:25 UTC, mattsse commented on src/backend.rs
> +type TransactionSender = UnboundedSender<DatabaseResult<WithOtherFields<Transaction>>>;
ah sorry, perhaps I wasn't clear enough on the issue, these oneshots are fine and we should keep using oneshot here,

the channel that we want to convert is this one

https://github.com/foundry-rs/foundry-fork-db/blob/40445d9931579f986da023e4fe16a4f16f9d48fb/src/backend.rs#L649-L649

https://github.com/foundry-rs/foundry-fork-db/blob/40445d9931579f986da023e4fe16a4f16f9d48fb/src/backend.rs#L572-L573

2024-08-10 04:09 UTC, DaniPopes approved these changes
lgtm, pending @mattsse

2024-08-10 09:42 UTC, mattsse approved these changes
nice

2024-08-10 09:43 UTC, merged